# Main menu
[[main]]
    name = "ğŸ  Home"
    url = "/"
    weight = 10
[[main]]
    name = "Content"
    params.header = true
    weight = 20
[[main]]
    name = "âœğŸ¼ Articles"
    url = "/articles"
    weight = 21
[[main]]
    name = "ğŸ–¥ï¸ Projects"
    url = "/portfolio"
    weight = 22
[[main]]
    name = "Hobbies"
    params.header = true
    weight = 30
[[main]]
    name = "ğŸ¤– Plamos"
    url = "/plamos"
    weight = 31
[[main]]
    name = "ğŸ“– Books"
    url = '/books'
    weight = 32

# Social menu
[[social]]
    name = "GitHub"
    url = "https://github.com/dorjnyamt"
    weight = 1
[[social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/dorjnyam"
    weight = 2
[[social]]
    name = "Email"
    url = "mailto:contact@dorjnyam.com"
    weight = 3